version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"   
      - "6831:6831/udp"   
      - "6832:6832/udp"   
      - "5778:5778"       
      - "16686:16686"     
      - "9411:9411"       
      - "4317:4317"       
      - "4318:4318"       
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - LOG_LEVEL=debug
    networks:
      - jaeger-network
    restart: unless-stopped

networks:
  jaeger-network:
    driver: bridge
